run:
  timeout: 3m

issues:
  exclude-rules:
    - linters:
        - exhaustivestruct
        - errcheck
        - err113
        - wrapcheck
        - gochecknoglobals
      path: _test\.go$

linters-settings:
  gocyclo:
    min-complexity: 18
  gocritic:
    enabled-checks:
      - appendCombine
      - boolExprSimplify
      - builtinShadow
      - commentedOutCode
      - commentedOutImport
      - docStub
      - dupImport
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - hexLiteral
      - hugeParam
      - importShadow
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - nilValReturn
      - octalLiteral
      - paramTypeCombine
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - sloppyReassign
      - stringXbytes
      - typeAssertChain
      - typeUnparen
      - unnecessaryBlock
      - weakCond
      - yodaStyleExpr

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exportloopref
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - err113
    - goimports
    - gci
    - mnd
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - nolintlint
    - wrapcheck
    - tparallel
    - stylecheck
    - prealloc
    - exhaustive
    - dogsled
    - dupl
    - gocognit
    - gosec
    - nestif
    - nakedret
